# Generated by Django 4.0.2 on 2022-02-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_text_post_transactionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='transactionId',
            new_name='transaction_id',
        ),
    ]
